#!/usr/bin/env bash

function say (){
	echo "=> $1"
}

if [ -d dist ] ; then
	say "Dist folder exists. Deleting all its contents."
	rm -R dist/*
	ls dist
else
	say "Creating dist folder"
	mkdir dist
fi

target_bundle="dist/YKC1P.app"

say "Copying base to $target_bundle"
cp -r "src/bundle_base.app" "$target_bundle"

say "Adding yubikey icon to application"
target_icon_path="$target_bundle/Contents/Resources/AutomatorApplet.icns"
rm "$target_icon_path"
cp "src/Yubikey.icns" "$target_icon_path"

say "Compressing Application as zip package"
zip -q -r "$target_bundle.zip" "$target_bundle"

echo
echo "OK. Results can be found in ./dist"