#!/usr/bin/env bash

function say (){
	echo "=> $1"
}

target=dist/YKC1P.app
icon_path="$target/Contents/Resources/applet.icns"

if [ -d dist ] ; then
	say "Dist folder exists. Deleting all its contents."
	rm -R dist/*
	ls dist
else
	say "Creating dist folder"
	mkdir dist
fi

say "Compiling to $target"
osacompile -o "$target" src/challenger.scpt

say "Adding yubikey icon to application"
rm "$icon_path"
cp src/yubikey.icns "$icon_path"

say "Compressing Application as zip package"
zip -q -r "$target.zip" "$target"

echo
echo "OK. Results can be found in ./dist"
